server:
  port: 8080

zos:
  api:
    baseUrl: ${ZOS_API_BASEURL:http://localhost:8089/zos}

spring:
  security:
    oauth2:
      client:
        registration:
          zos:
            client-id: demo-client
            client-secret: demo-secret
            authorization-grant-type: client_credentials
            scope: zos.read
        provider:
          zos:
            token-uri: ${OAUTH_TOKEN_URI:http://localhost:8089/oauth/token}
      resourceserver:
        jwt:
          jwk-set-uri: ${OAUTH_JWKS_URI:http://localhost:8089/oauth/jwks}
